# Mastra-Hono Project Shortcuts
# Generated by scripts/setup-nushell.nu on 2026-03-09 10:23:15

source '/Users/petersmith/Dev/GitHub/mastra-hono/src/mastra/tools/nushell-aliases.nu'
source '/Users/petersmith/Dev/GitHub/mastra-hono/src/mastra/tools/nushell-utils.nu'
source '/Users/petersmith/Dev/GitHub/mastra-hono/src/mastra/tools/help-aliases.nu'

# Additional project-specific environment variables
$env.MASTRA_PROJECT_ROOT = '/Users/petersmith/Dev/GitHub/mastra-hono'

print 'Mastra project shortcuts loaded.'
