# scripts/setup-nushell.nu
# Setup script to link Mastra-Hono project shortcuts to the user's Nushell configuration.

let project_root = ( $env.FILE_PWD | path dirname )
let user_config = ($nu.config-path)

print $"Project root detected as: ($project_root)"
print $"User configuration file: ($user_config)"

# Files to source
let alias_file = ($project_root | path join "src" "mastra" "tools" "nushell-aliases.nu")
let utils_file = ($project_root | path join "src" "mastra" "tools" "nushell-utils.nu")
let help_file = ($project_root | path join "src" "mastra" "tools" "help-aliases.nu")

# Create a project-specific entry point with absolute paths
let project_entry_file = ($project_root | path join "nu" "project-shortcuts.nu")

print $"Generating ($project_entry_file)..."

let entry_content = $"# Mastra-Hono Project Shortcuts
# Generated by scripts/setup-nushell.nu on (date now | format date '%Y-%m-%d %H:%M:%S')

source '($alias_file)'
source '($utils_file)'
source '($help_file)'

# Additional project-specific environment variables
$env.MASTRA_PROJECT_ROOT = '($project_root)'

print 'Mastra project shortcuts loaded.'
"

$entry_content | save --force $project_entry_file

# Add to user config if not present
let config_content = (open $user_config | into string)
let source_line = $"source '($project_entry_file)'"

if ($config_content | str contains $project_entry_file) {
    print $"Already sourced in ($user_config)"
} else {
    print $"Adding source line to ($user_config)..."
    $"\n# Mastra-Hono Project Shortcuts\n($source_line)\n" | save --append $user_config
    print "Successfully updated Nushell configuration."
}

print "\nSetup complete! Please restart Nushell or run:"
print $"source '($user_config)'"
