/**
 * Docs Command - Trigger Docmd documentation generation
 *
 * Runs the docmd CLI to generate documentation and llms.txt
 */

import { existsSync } from 'fs';
import { join, resolve } from 'path';

export async function runDocsCommand(args: string[]) {
  console.log('📚 Generating documentation with Docmd...');

  const configPath = resolve(join(import.meta.dir, '..', '..', 'docs', 'docmd.config.ts'));

  // Check if docmd config exists
  if (!existsSync(configPath)) {
    console.log('⚠️  Docmd config not found at:', configPath);
    console.log('   Creating placeholder llms.txt...');
    await generatePlaceholderLlms();
    return;
  }

  console.log('   Found config:', configPath);

  try {
    // Run docmd CLI
    const { spawn } = await import('child_process');

    const proc = spawn('bunx', ['docmd', 'build', '--config', configPath], {
      cwd: resolve(join(import.meta.dir, '..', '..')),
      stdio: 'inherit',
    });

    let docmdExitCode = 0;

    await new Promise((resolve, reject) => {
      proc.on('close', (code) => {
        docmdExitCode = code ?? 0;
        resolve(docmdExitCode);
      });
      proc.on('error', reject);
    });

    // Only copy files if docmd succeeded
    if (docmdExitCode !== 0) {
      console.log('\n⚠️  Docmd build failed (exit code: ' + docmdExitCode + ')');
      console.log('   Falling back to placeholder llms.txt...');
      await generatePlaceholderLlms();
      return;
    }

    // Copy llms files to docs folder for agent access
    const siteLlms = resolve(join(import.meta.dir, '..', '..', 'docs-site', 'llms.txt'));
    const siteLlmsFull = resolve(join(import.meta.dir, '..', '..', 'docs-site', 'llms-full.txt'));
    const docsLlms = resolve(join(import.meta.dir, '..', '..', 'docs', 'llms.txt'));
    const docsLlmsFull = resolve(join(import.meta.dir, '..', '..', 'docs', 'llms-full.txt'));

    if (existsSync(siteLlms) && existsSync(siteLlmsFull)) {
      const { copyFileSync } = await import('fs');
      copyFileSync(siteLlms, docsLlms);
      copyFileSync(siteLlmsFull, docsLlmsFull);
      console.log('\n✅ Documentation generated successfully');
      console.log('📄 llms.txt copied to docs/ folder');
    } else if (existsSync(siteLlms)) {
      console.log('\n⚠️  llms-full.txt not found, copying llms.txt only');
      const { copyFileSync } = await import('fs');
      copyFileSync(siteLlms, docsLlms);
    } else {
      console.log('\n⚠️  Docmd completed but llms.txt not found');
      console.log('   Falling back to placeholder...');
      await generatePlaceholderLlms();
    }
  } catch (error) {
    console.error('❌ Docmd build failed:', error);
    console.log('\n⚠️  Falling back to placeholder llms.txt');
    await generatePlaceholderLlms();
  }
}

async function generatePlaceholderLlms() {
  const { writeFileSync } = await import('fs');

  const docsDir = resolve(join(import.meta.dir, '..', '..', 'docs'));

  // ⚠️  NOTICE: This is a placeholder, not real Docmd output
  const llmsContent = `# LLMS - Root Level Visibility (PLACEHOLDER)

> ⚠️  **This is a placeholder file.** Run \`bun scripts/dev.ts docs\` after installing
> \`@docmd/core\` to generate the real documentation index.

## Directories

- \`/briefs\` - Active mission parameters and briefs
- \`/playbooks\` - Pattern playbooks (TTS v2.0, UI-Color, etc.)
- \`/debriefs\` - Post-mortem analysis
- \`/scripts\` - Utility CLI (dev-box)

## Technology Stack

| Tier | Location | Strictness |
|------|----------|------------|
| Tier 1: Sieve | /scripts/lab | @ts-nocheck |
| Tier 2: Net | /scripts/commands | Moderate |
| Tier 3: Edifice | /src | strict: true |

Generated by dev-box (placeholder)
`;

  const llmsPath = join(docsDir, 'llms.txt');
  writeFileSync(llmsPath, llmsContent);
  console.log(`⚠️  Created placeholder llms.txt - not using real Docmd output`);
  console.log(`   Run: bun add @docmd/core @docmd/plugin-llms`);
  console.log(`   Then: bun scripts/dev.ts docs`);
}
