/**
 * Docs Command - Trigger Docmd documentation generation
 *
 * Runs the docmd CLI to generate documentation and llms.txt
 * Includes post-processing to clean up generated files
 */

import { existsSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';

export async function runDocsCommand(args: string[]) {
  console.log('📚 Generating documentation with Docmd...');

  const configPath = resolve(join(import.meta.dir, '..', '..', 'docs', 'docmd.config.ts'));

  // Check if docmd config exists
  if (!existsSync(configPath)) {
    console.log('⚠️  Docmd config not found at:', configPath);
    console.log('   Creating placeholder llms.txt...');
    await generatePlaceholderLlms();
    return;
  }

  console.log('   Found config:', configPath);

  try {
    // Run docmd CLI
    const { spawn } = await import('child_process');

    const proc = spawn('bunx', ['docmd', 'build', '--config', configPath], {
      cwd: resolve(join(import.meta.dir, '..', '..')),
      stdio: 'inherit',
    });

    let docmdExitCode = 0;

    await new Promise((resolve, reject) => {
      proc.on('close', (code) => {
        docmdExitCode = code ?? 0;
        resolve(docmdExitCode);
      });
      proc.on('error', reject);
    });

    // Only process files if docmd succeeded
    if (docmdExitCode !== 0) {
      console.log('\n⚠️  Docmd build failed (exit code: ' + docmdExitCode + ')');
      console.log('   Falling back to placeholder llms.txt...');
      await generatePlaceholderLlms();
      return;
    }

    // Define paths
    const docsSiteDir = resolve(join(import.meta.dir, '..', '..', 'docs-site'));
    const siteLlms = join(docsSiteDir, 'llms.txt');
    const siteLlmsFull = join(docsSiteDir, 'llms-full.txt');
    const docsDir = resolve(join(import.meta.dir, '..', '..', 'docs'));
    const docsLlms = join(docsDir, 'llms.txt');
    const docsLlmsFull = join(docsDir, 'llms-full.txt');

    if (existsSync(siteLlms)) {
      // Post-process and copy llms.txt
      let llmsContent = readFileSync(siteLlms, 'utf8');
      llmsContent = cleanLlmsContent(llmsContent);
      // Append source documentation map
      llmsContent += generateSourceDocMap();
      writeFileSync(docsLlms, llmsContent, 'utf8');
      console.log('✅ Cleaned llms.txt written to docs/');
    }

    if (existsSync(siteLlmsFull)) {
      // Post-process and copy llms-full.txt
      let fullContent = readFileSync(siteLlmsFull, 'utf8');
      fullContent = cleanLlmsContent(fullContent);
      writeFileSync(docsLlmsFull, fullContent, 'utf8');
      console.log('✅ Cleaned llms-full.txt written to docs/');
    }

    if (!existsSync(siteLlms) && !existsSync(siteLlmsFull)) {
      console.log('\n⚠️  Docmd completed but llms files not found');
      console.log('   Falling back to placeholder...');
      await generatePlaceholderLlms();
      return;
    }

    console.log('\n✅ Documentation generated successfully');
  } catch (error) {
    console.error('❌ Documentation generation failed:', error);
    console.log('\n⚠️  Falling back to placeholder llms.txt');
    await generatePlaceholderLlms();
  }
}

/**
 * Clean llms.txt content:
 * 1. URL-encode spaces in links
 * 2. Remove "Untitled" entries
 * 3. Remove "Folders:" and metadata-only entries
 */
function cleanLlmsContent(content: string): string {
  // 1. URL-encode spaces in markdown links
  // [Title](url with spaces) -> [Title](url%20with%20spaces)
  // Handles both .md links and stripped URLs
  content = content.replace(/\[([^\]]*)\]\(([^)]+)\)/g, (match, title, url) => {
    // Skip if already encoded or if it's a header blockquote
    if (url.includes('%20') || url.startsWith('>')) return match;
    // Skip "Generated by" and other header lines
    if (title.includes('Generated')) return match;
    // Skip empty titles
    if (!title || title.trim() === '') return match;
    // URL-encode spaces in the URL portion
    const encodedUrl = url.replace(/ /g, '%20');
    return `[${title}](${encodedUrl})`;
  });

  // 2. Remove "Untitled" entries (lines that are just "- [Untitled]" or contain "Untitled" at start)
  content = content
    .split('\n')
    .filter((line) => {
      // Skip standalone "Untitled" link lines
      if (line.match(/^-\s+\[Untitled\]/)) return false;
      // Skip "Folders:" metadata lines
      if (line.includes('Folders:')) return false;
      // Skip empty lines after filtering
      if (line.trim() === '') return false;
      return true;
    })
    .join('\n');

  // 3. Clean up consecutive empty lines
  content = content.replace(/\n{3,}/g, '\n\n');

  return content;
}

async function generatePlaceholderLlms() {
  const docsDir = resolve(join(import.meta.dir, '..', '..', 'docs'));

  // ⚠️  NOTICE: This is a placeholder, not real Docmd output
  const llmsContent = `# LLMS - Root Level Visibility (PLACEHOLDER)

> ⚠️  **This is a placeholder file.** Run \`bun scripts/dev.ts docs\` after installing
> \`@docmd/core\` to generate the real documentation index.

## Directories

- \`/briefs\` - Active mission parameters and briefs
- \`/playbooks\` - Pattern playbooks (TTS v2.0, UI-Color, etc.)
- \`/debriefs\` - Post-mortem analysis
- \`/scripts\` - Utility CLI (dev-box)

## Technology Stack

| Tier | Location | Strictness |
|------|----------|------------|
| Tier 1: Sieve | /scripts/lab | @ts-nocheck |
| Tier 2: Net | /scripts/commands | Moderate |
| Tier 3: Edifice | /src | strict: true |

Generated by dev-box (placeholder)
`;

  const llmsPath = join(docsDir, 'llms.txt');
  writeFileSync(llmsPath, llmsContent, 'utf8');
  console.log(`⚠️  Created placeholder llms.txt - not using real Docmd output`);
  console.log(`   Run: bun add @docmd/core @docmd/plugin-llms`);
  console.log(`   Then: bun scripts/dev.ts docs`);
}

/**
 * Generate Source Documentation Map
 *
 * Scans /src for README.md files and generates a structured map
 * of the source code documentation.
 */
function generateSourceDocMap(): string {
  const srcDir = resolve(join(import.meta.dir, '..', '..', 'src'));

  if (!existsSync(srcDir)) {
    return '';
  }

  const readmeFiles = findReadmeFiles(srcDir, srcDir);

  if (readmeFiles.length === 0) {
    return '';
  }

  let output = '\n---\n\n## Source Documentation (Doc Map)\n\n';

  // Deduplicate by full URL
  const seenUrls = new Set<string>();

  for (const { path: filePath, title } of readmeFiles) {
    // Convert src/foo/README.md -> /src/foo/
    let relativePath = filePath.replace(srcDir, '').replace(/\/README\.md$/i, '').replace(/\.md$/i, '');
    // Handle root src/README.md case
    if (relativePath === '') {
      relativePath = '/';
    } else if (!relativePath.startsWith('/')) {
      relativePath = '/' + relativePath;
    }
    // Ensure no double slashes and handle trailing slash
    const cleanPath = ('/src' + relativePath).replace(/\/\//g, '/').replace(/\/$/, '');
    const fullUrl = 'https://polyvis.local' + (cleanPath || '/src') + '/';

    // Skip duplicates (from docmd's own processing)
    if (seenUrls.has(fullUrl)) {
      continue;
    }
    seenUrls.add(fullUrl);

    output += `- [${title}](${fullUrl})\n`;
  }

  return output;
}

/**
 * Recursively find README.md files in a directory
 */
function findReadmeFiles(
  dir: string,
  rootDir: string
): Array<{ path: string; title: string }> {
  const results: Array<{ path: string; title: string }> = [];

  try {
    const entries = readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(dir, entry.name);

      if (entry.isDirectory()) {
        // Skip node_modules and hidden directories
        if (entry.name === 'node_modules' || entry.name.startsWith('.')) {
          continue;
        }
        // Recurse into subdirectories
        results.push(...findReadmeFiles(fullPath, rootDir));
      } else if (entry.isFile()) {
        // Check for README.md files (case-insensitive)
        if (entry.name.toLowerCase() === 'readme.md') {
          const title = extractTitleFromReadme(fullPath, entry.name);
          results.push({ path: fullPath, title });
        }
      }
    }
  } catch {
    // Ignore permission errors
  }

  return results;
}

/**
 * Extract title from README.md file
 */
function extractTitleFromReadme(filePath: string, fallbackName: string): string {
  try {
    const content = readFileSync(filePath, 'utf8');

    // Try YAML frontmatter title
    const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
    if (fmMatch) {
      const titleMatch = fmMatch[1].match(/^title:\s*"?([^"\n]+)"?/m);
      if (titleMatch) {
        return titleMatch[1].trim();
      }
    }

    // Try H1 heading
    const h1Match = content.match(/^#\s+(.+)$/m);
    if (h1Match) {
      return h1Match[1].trim();
    }

    // Fallback: prettify filename
    return fallbackName.replace(/\.md$/i, '').replace(/[-_]/g, ' ');
  } catch {
    return fallbackName.replace(/\.md$/i, '');
  }
}
