/**
 * Docs Command - Trigger Docmd documentation generation
 * 
 * Runs the docmd CLI to generate documentation and llms.txt
 */

import { resolve, join } from 'path';
import { existsSync } from 'fs';

export async function runDocsCommand(args: string[]) {
  console.log('📚 Generating documentation with Docmd...');
  
  const configPath = resolve(join(import.meta.dir, '..', '..', 'docs', 'docmd.config.ts'));
  
  // Check if docmd config exists
  if (!existsSync(configPath)) {
    console.log('⚠️  Docmd config not found at:', configPath);
    console.log('   Creating placeholder llms.txt...');
    await generatePlaceholderLlms();
    return;
  }

  console.log('   Found config:', configPath);

  try {
    // Run docmd CLI
    const { spawn } = await import('child_process');
    
    const proc = spawn('bunx', ['docmd', 'build', '--config', configPath], {
      cwd: resolve(join(import.meta.dir, '..', '..')),
      stdio: 'inherit',
    });
    
    await new Promise((resolve, reject) => {
      proc.on('close', (code) => {
        if (code === 0) {
          resolve(code);
        } else {
          console.log('\n⚠️  Docmd build completed with warnings');
          resolve(code);
        }
      });
      proc.on('error', reject);
    });
    
    // Copy llms files to docs folder for agent access
    const distLlms = resolve(join(import.meta.dir, '..', '..', 'dist', 'llms.txt'));
    const distLlmsFull = resolve(join(import.meta.dir, '..', '..', 'dist', 'llms-full.txt'));
    const docsLlms = resolve(join(import.meta.dir, '..', '..', 'docs', 'llms.txt'));
    const docsLlmsFull = resolve(join(import.meta.dir, '..', '..', 'docs', 'llms-full.txt'));
    
    if (existsSync(distLlms)) {
      const { copyFileSync } = await import('fs');
      copyFileSync(distLlms, docsLlms);
      copyFileSync(distLlmsFull, docsLlmsFull);
      console.log('\n✅ Documentation generated successfully');
      console.log('📄 llms.txt copied to docs/ folder');
    }
    
  } catch (error) {
    console.error('❌ Documentation generation failed:', error);
    console.log('   Falling back to placeholder generation...');
    await generatePlaceholderLlms();
  }
}

async function generatePlaceholderLlms() {
  const { writeFileSync } = await import('fs');
  const { resolve, join } = await import('path');
  
  const docsDir = resolve(join(import.meta.dir, '..', '..', 'docs'));

  const llmsContent = `# LLMS - Root Level Visibility

## Directories

- \`/briefs\` - Active mission parameters and briefs
- \`/playbooks\` - Pattern playbooks (TTS v2.0, UI-Color, etc.)
- \`/debriefs\` - Post-mortem analysis
- \`/scripts\` - Utility CLI (dev-box)

## Technology Stack

| Tier | Location | Strictness |
|------|----------|------------|
| Tier 1: Sieve | /scripts/lab | @ts-nocheck |
| Tier 2: Net | /scripts/commands | Moderate |
| Tier 3: Edifice | /src | strict: true |

Generated by dev-box
`;

  const llmsPath = join(docsDir, 'llms.txt');
  writeFileSync(llmsPath, llmsContent);
  console.log(`✅ Placeholder llms.txt created at: ${llmsPath}`);
}
